### PR TITLE
Try a workaround for is_valid / broken connection check

### PR DESCRIPTION
**Pull request by geomaniac**
This is definitely not optimal, but it seems to fix the problem.

With this we can enable `test_on_check_out` on the r2d2 pool which in turn fixes the problem with broken connections poisoning the pool (once a connection was broken it always failed but was never removed or reconnected)

### CODE REVIEW

**Comment by weiznich** [comment]
That certainly works, but I would prefer a less hacky solution.
Probably something like this:
* Mark [this function](https://github.com/GiGainfosystems/diesel/blob/giga_compat/diesel/src/r2d2.rs#L89) as `default`  impl
* Just override it inside of `diesel_oci` using specialisation

(I think we already use specialisation in some cases, so this wouldn't add any new unstable feature)

**Comment by geomaniac** [comment]
I think something like your proposed solution was tried before, but wasn't successful. (@pgab would know more here)

Just out of curiosity, how would I even mark a function implemented as part of a trait implementation as default impl?

**Comment by weiznich** [comment]
> I think something like your proposed solution was tried before, but wasn't successful. (@pgab would know more here)

I will try to have a look at this later today. I do not see way it shouldn't work 🙈 

> Just out of curiosity, how would I even mark a function implemented as part of a trait implementation as default impl?

Just add `default` in front of the function/impl you want to specialize. See [this example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=30a189a0fbef2af2bf510ed69ab11b03)

**Comment by geomaniac** [comment]
> I will try to have a look at this later today. I do not see way it shouldn't work 🙈

Sure, give it a shot. Keep in mind that this is an actual problem on a customer installation and a fix should be able to run atop of our master.

> [..] default

Ah, this seems to be part of `specialization`. To be honest, I am rather uninformed about the details of nightly/unstable features.

**Comment by geomaniac** [comment]
Note: Workaround for #5,

**Comment by geomaniac** [comment]
Superseded by #28

**Pull request closed without merging**
